// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A UTF-8 path rendered using an explicitly selected native path convention.
 *
 * "Native" refers to the supplied [`PathConvention`], which may be foreign to
 * the operating system running this process. Construction retains the wire
 * spelling without applying host path rules; callers validate and normalize
 * it by converting to a [`PathUri`] with an explicit convention.
 */
export type NativePathString = string;
